[project]
name = "google-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kernel>=0.8.0",
    "patchright>=1.52.5",
    "playwright>=1.53.0",
]
