[project]
name = "github"
version = "0.1.0"
description = "Github automations"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["kernel>=0.8.0", "playwright>=1.52.0"]

[dependency-groups]
dev = ["mypy>=1.15.0"]
